"""Init

Revision ID: 428b7bfb6773
Revises: 
Create Date: 2021-12-13 17:19:42.396758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428b7bfb6773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###
